[[objects]]
type = "sphere"
position = [0.0, 1.5, 0.0]
radius = 1.0
material = "reflective"

[[objects]]
type = "sphere"
position = [2.0, 1.0, 0.0]
radius = 1.0
material = "white"

[[objects]]
type = "sphere"
position = [-2.0, 1.0, 0.0]
radius = 1.0
material = "black"

[[objects]]
type = "cube"
min = [-0.75, 0.0, 3.0]
max = [0.75, 1.5, 5.0]
material = "blue"

[[objects]]
type = "sphere"
position = [0.0, 2000.0, 100.0]
radius = 900.0
material = "red"

[[objects]]
type = "quad"
point1 = [100.0, 0.0, 100.0]
point2 = [100.0, 0.0, 10.0]
point3 = [-100.0, 0.0, 10.0]
point4 = [-100.0, 0.0, 100.0]
scale = [100.0, 100.0]
material = "checkered"

[[lights]]
type = "point"
position = [0.0, 4.0, 0.0]
color = [1.0, 1.0, 1.0]

[camera]
position = [0.0, 0.5, 3.0]
rotation = [0.0, 0.0, -1.0]

[skybox]
color = [0.0, 0.0, 0.0]
