[[objects]]
type = "sphere"
position = [0.0, 1.5, 0.0]
radius = 1.0
material = "reflective"

[[objects]]
type = "sphere"
position = [2.0, 1.0, 0.0]
radius = 1.0
material = "red"

[[objects]]
type = "sphere"
position = [-2.0, 1.0, 0.0]
radius = 1.0
material = "red"

[[objects]]
type = "sphere"
position = [0.0, 2000.0, 100.0]
radius = 900.0
material = "red"

[[objects]]
type = "quad"
point1 = [1.0, 0.0, 1.0]
point2 = [1.0, 0.0, -1.0]
point3 = [-1.0, 0.0, -1.0]
point4 = [-1.0, 0.0, 1.0]
material = "checkered"

[[lights]]
type = "point"
position = [0.0, 5.0, 0.0]
color = [1.0, 1.0, 1.0]

[camera]
position = [0.0, 0.5, 3.0]
direction = [0.0, 0.0, -1.0]

[skybox]
color = [0.0, 0.0, 0.0]
