name: render

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: render-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - name: extract OIDN
        run: |
          rm -rf oidn/oidn
          tar -xzf oidn/oidn-2.4.1.x86_64.linux.tar.gz -C oidn
          mv oidn/oidn-2.4.1.x86_64.linux oidn/oidn

      - name: render
        run: |
          export LD_LIBRARY_PATH=./oidn/oidn/lib:$LD_LIBRARY_PATH
          cargo run --locked --release -F oidn -- --multiplier=4 --all
          cargo test --locked --release -F oidn --all-targets --all

      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull --rebase --autostash
          git add renders
          if git diff --cached --quiet; then
            echo "No render changes to commit"
          else
            git commit -m "render"
            git push
          fi
