on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "render"
  cancel-in-progress: true

jobs:
  render:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.github_token }}
          submodules: recursive

      - uses: dtolnay/rust-toolchain@nightly

      - name: render
        run: |
          export LD_LIBRARY_PATH=./oidn/oidn/lib:$LD_LIBRARY_PATH
          cargo run --release -F oidn -- --multiplier=4 --all
          cargo test --release -F oidn --all-targets --all

      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git pull --autostash
          git add renders
          git commit -m "render"
          git push
