on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "tests"
  cancel-in-progress: true

jobs:
  tests:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.github_token }}
          submodules: recursive

      - name: rust
        run: |
          curl --proto '=https' --tlsv1.2 -ssf https://sh.rustup.rs -o rustup.sh
          sh rustup.sh --default-toolchain nightly --profile minimal -y
          rustup component add rustfmt clippy --toolchain nightly
          source "$home/.cargo/env"
          rustup update

      - name: test
        run: |
          cargo test --release --all-features --all-targets --all

      - name: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add tests
          git commit -m "tests"
          git push
