name: tests

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}

jobs:
  tests:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      - name: extract OIDN
        run: |
          rm -rf oidn/oidn
          tar -xzf oidn/oidn-2.4.1.x86_64.linux.tar.gz -C oidn
          mv oidn/oidn-2.4.1.x86_64.linux oidn/oidn

      - name: test
        run: |
          export LD_LIBRARY_PATH=./oidn/oidn/lib:$LD_LIBRARY_PATH
          cargo fmt --all --check
          cargo clippy --locked --all-targets --all-features --workspace -- -D warnings
          cargo test --locked --release --all-features --all-targets --all
